# Generated by Django 4.2.7 on 2023-11-09 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='username')),
                ('user_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='user_id')),
                ('full_name', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('profile_image_url', models.URLField(default='https://img.freepik.com/free-vector/hacker-operating-laptop-cartoon-icon-illustration-technology-icon-concept-isolated-flat-cartoon-style_138676-2387.jpg?w=740&t=st=1699500630~exp=1699501230~hmac=b24973b64cc2f563099c02f0f0d0fde3caa3611bcf086fc17674934db52b887f', max_length=1000, verbose_name='profile_image_url')),
                ('bg_image_url', models.URLField(default='https://img.freepik.com/free-photo/free-photo-black-grunge-abstract-background-pattern-wallpaper_1340-34108.jpg?t=st=1699500772~exp=1699504372~hmac=658dd763edb14036f4525432330b4e7a8eaaf237430b17d952d1572cd64eadeb&w=740', max_length=1000, verbose_name='bg_image_url')),
                ('is_mentor', models.BooleanField(default=False, verbose_name='is_mentor')),
                ('bio', models.TextField(blank=True)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'user_id'], name='profiles_us_usernam_051fff_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('url', models.URLField(verbose_name='url')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='User Links')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'db_table': 'user_links',
            },
        ),
        migrations.CreateModel(
            name='UserIntrests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.topics', verbose_name='Intrested Topics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Intrested users')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True, verbose_name='position')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Mentor Profile')),
            ],
        ),
    ]
