FROM python:3

ENV PYTHONUNBUFFERED 1

FROM python:3

# Set the working directory for the rest of the commands
WORKDIR /profile-svc-codenation

# Copy the contents of the current directory into the container
COPY . .

# Install Python dependencies
RUN pip install -r requirements.txt

# Expose the port on which your Django application will run
EXPOSE 50051

# Set the working directory to the 'profiles' directory
WORKDIR /profile-svc-codenation/profiles

# Run the Django server script
CMD ["python3", "server.py"]

