FROM python:3

ENV PYTHONUNBUFFERED 1

RUN mkdir /profile-svc-codenation

WORKDIR /profile-svc-codenation

COPY . .

RUN pip install -r requirements.txt

EXPOSE 8000

RUN python3 manage.py runserver 0.0.0.0:8000 
